db:
 user: "![MFNM2WBbu1GkzU/wZzzerQ==]"
 password: "![rrNmWPr8GJUSlot9BdCzFQ==]"

sf:
 user: "![uRNbK37wYhkqK6t3hlaRmnP7gT8XbDHu9NHOsFnJt1E=]"
 password: "![qEjKlBpGt4l39w5uc0GMqTc12lRnUnls]"
 token: "![lQ4td8f9olOA53bCOW5eOOtbasqclA2pNXVVT9kiMME=]"

email:
 password: "![qI3G9kKsq2L8Gm0l/Q7GMhkskqpjjKHV]"

https:
 password: "![wlT9Uy+XwHa1j4MO2d09XA==]"